title: 'SleekGrid'
description: 'A modern Data Grid / Spreadsheet component (inspired by SlickGrid)'
baseurl: /sleekgrid

packageurl:
    bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@5.2.0
    jquery: https://cdn.jsdelivr.net/npm/jquery@3.6.0
    jqueryui: https://cdn.jsdelivr.net/npm/jquery-ui@1.13.2
    sleekgrid: https://cdn.jsdelivr.net/npm/@serenity-is/sleekgrid@1.9.6
    slickgrid: https://cdn.jsdelivr.net/npm/slickgrid@2.4.45

srcurl:
    docs: https://github.com/serenity-is/sleekgrid/blob/main/docs

defaults:
    -
        scope:
            path: ''
        values:
            layout: default
    -
        scope:
            path: 'examples'
        values:
            layout: examples
    -
        scope:
            path: 'examples/classic'
        values:
            layout: layout-classic-examples
